<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>Adding Annotations</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Adding Annotations</h1>



<p>Typically you have raw onset data when loading files with
<code>onsetsync</code> which might not any other information within them
(beat subdivisions, etc.). Here is an example of how you can add
reference beat subdivisions and calculate reference beats such as mean
of all onsets in a sub-division.</p>
<div id="load-raw-onsets-from-osf" class="section level2">
<h2>Load raw onsets from OSF</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(onsetsync)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(httr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>CSS_Song2_Onset <span class="ot">&lt;-</span> <span class="fu">get_OSF_csv</span>(<span class="st">&#39;8a347&#39;</span>) <span class="co"># Get onsets</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(CSS_Song2_Onset[,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,]))</span></code></pre></div>
<pre><code>##    Piece Label.SD SD Clave_. Section Isochronous.SD.Time Clave     Bass
## 1 Song_2      1|1  1       1     Son            5.037333    NA       NA
## 2 Song_2      1|2  2       N     Son            5.260063    NA       NA
## 3 Song_2      1|3  3       N     Son            5.482792    NA       NA
## 4 Song_2      1|4  4       2     Son            5.705521    NA 5.714555
## 5 Song_2      1|5  5       N     Son            5.928250    NA 5.927078
## 6 Song_2      1|6  6       N     Son            6.150979    NA       NA</code></pre>
<p>The data frame shows a portion of the onset data structure where the
last three columns refer to the onset times of the specific instruments
(<code>Clave</code>, <code>Bass</code>, and <code>Guitar</code>). Note
that we only show the first eight columns and 6 rows. The first five
columns are <strong>meta-data</strong>, referring to the piece, beats
and cycles and sections. <code>Label.SD</code> combines cycle and beat
information (first integer refers to cycle and the second integer refers
to beat sub-division). <code>SD</code> represents the
<em>sub-division</em> explicitly. In this music there are 16
subdivisions per cycle (which can be felt as 4 beats <span class="math inline">\(\times\)</span> 4 subdivisions).
<code>Section</code> indicates the specific part of the piece. Finally,
in this example we have <code>Clave_</code> column, which is a reference
to a clave pattern: strokes of the clave (woodblocks), whether sounded
or not, are noted here; there are normally 5 strokes per cycle. The
onset times for the instruments are recorded in seconds, although we
prefer to use milliseconds (ms) in the analyses of synchrony to avoid
reporting unnecessarily many digits. The onset times of the instruments
are the result of an automatic onset detection (that has been subjected
manual check) and the exact technique may depend on instrument used and
source of data.</p>
</div>
<div id="add-annotations-for-cycles" class="section level2">
<h2>Add annotations for cycles</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>CSS_Song2_Metre <span class="ot">&lt;-</span> <span class="fu">get_OSF_csv</span>(<span class="st">&#39;4cdpr&#39;</span>) <span class="co"># Annotations for cycles</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(CSS_Song2_Metre))</span></code></pre></div>
<pre><code>##   Cycle      Time
## 1     1  5.037333
## 2     2  8.601000
## 3     3 12.123000
## 4     4 15.672000
## 5     5 19.174500
## 6     6 22.686000</code></pre>
<p>Let’s simplify this example (select only few columns).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>CSS_Song2_Onset <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(CSS_Song2_Onset,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                  Label.SD,SD,Clave,Bass,Guitar,Tres) </span></code></pre></div>
<p>In the second data frame (<code>CSS_Song2_Metre</code>), shown in
Table 2, we have annotations, namely the cycle times, which are the
manually-estimated times when the cycles start (containing all
sub-divisions of the beat). For instance, here the first cycle starts at
5.037333, the second cycle at 8.601000) and so on. This is important
information for some type of analyses and often we want to combine the
automatically detected onset times and the annotated cycles. It is
important to realise that the information about the cycles comes from an
annotation of the music by an expert (or in some cases by several
experts). To get an annotation such as this, software such <em>Sonic
Visualiser</em> can be used to tap with the perceived beats of the audio
track to obtain the beat times and then the first beat of the cycle is
manually labelled to the data. The sub-divisions are then inferred from
the cycle beginnings. This annotation process requires expertise with
the musical style in question as the same patterns of onsets could
potentially give rise to multiple interpretations of the metre.</p>
</div>
<div id="combine-onsets-and-annotations" class="section level2">
<h2>Combine onsets and annotations</h2>
<p>As the onsets and annotations are in different files, we first
combine the onsets and annotations with <code>onsetsync</code>. Here we
first add annotations about the cycles into the onset data and then we
also add isochronous beat times to the data frame, since are useful
reference points for future calculations. The metre annotations have
already informed the allocation of onsets to beat positions; here we add
more information from the metre annotations to the dataframe to allow
further analysis options.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add annotations about the cycle to the data frame</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>CSS_Song2 <span class="ot">&lt;-</span> <span class="fu">add_annotation</span>(<span class="at">df =</span> CSS_Song2_Onset,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">annotation =</span> CSS_Song2_Metre<span class="sc">$</span>Cycle,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">time =</span> CSS_Song2_Metre<span class="sc">$</span>Time,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">reference =</span> <span class="st">&#39;Label.SD&#39;</span>)</span></code></pre></div>
</div>
<div id="add-isochronous-beat-subdivisions-based-on-annotation" class="section level2">
<h2>Add isochronous beat subdivisions based on annotation</h2>
<p>We add an isochronous reference subdivision of beat subdivisions
based on annotated cycle start times.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add isochronous beats to the data frame</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>CSS_Song2 <span class="ot">&lt;-</span> <span class="fu">add_isobeats</span>(<span class="at">df =</span> CSS_Song2, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">instr =</span> <span class="st">&#39;CycleTime&#39;</span>, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">beat =</span> <span class="st">&#39;SD&#39;</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(CSS_Song2[,<span class="dv">2</span><span class="sc">:</span><span class="dv">9</span>]))</span></code></pre></div>
<pre><code>##   SD Clave     Bass   Guitar     Tres CycleTime Cycle Isochronous.SD.Time
## 1  1    NA       NA       NA       NA  5.037333     1            5.037333
## 2  2    NA       NA 5.281932       NA        NA     1            5.260062
## 3  3    NA       NA 5.480643       NA        NA     1            5.482792
## 4  4    NA 5.714555 5.707537 5.730943        NA     1            5.705521
## 5  5    NA 5.927078 5.939071 5.917083        NA     1            5.928250
## 6  6    NA       NA 6.153243 6.144901        NA     1            6.150979</code></pre>
<p>At this point we have the basic elements for most analyses. In the
data frame <code>CSS_Song2</code> we have the onset data (coded under
instrument names, here <code>Clave</code>, <code>Bass</code>, and
<code>Tres</code>) and information about the beat cycles
(<code>CycleTime</code> and <code>Cycle</code>), and we also have timing
information for isochronous beat divisions
(<code>Isochronous.SD.Time</code>).</p>
<p>These annotation-based virtual beat structures can be systematically
off by a certain amount, so perhaps some it may be advantageous for some
analyses to infer the timing information related to the beat structure
from the existing onsets themselves and not rely on external reference.
<code>add_isobeats</code> function can accomplish this if given the
instruments from which it will calculate the mean onset time for the
first beat of the cycle, which will then be used to set the isochronous
beat timings for the rest of the beats within the cycle.</p>
</div>
<div id="add-isochronous-beat-subdivisions-based-on-mean-onset-times" class="section level2">
<h2>Add isochronous beat subdivisions based on mean onset times</h2>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(CSS_Song2)[<span class="dv">9</span>] <span class="ot">&lt;-</span> <span class="st">&#39;Ann.Iso&#39;</span> <span class="co"># Rename</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Add isochronous beats based on mean timing of guitar, tres, and clave</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>CSS_Song2 <span class="ot">&lt;-</span> <span class="fu">add_isobeats</span>(<span class="at">df =</span> CSS_Song2, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">instr =</span> <span class="fu">c</span>(<span class="st">&#39;Guitar&#39;</span>,<span class="st">&#39;Tres&#39;</span>,<span class="st">&#39;Clave&#39;</span>), </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">beat =</span> <span class="st">&#39;SD&#39;</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the newly calculated isochronous beat times </span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># from the second cycle onwards.</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(CSS_Song2[<span class="dv">17</span><span class="sc">:</span><span class="dv">22</span>,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>)]))</span></code></pre></div>
<pre><code>##    SD     Tres CycleTime Cycle  Ann.Iso Isochronous.SD.Time
## 17  1 8.571167     8.601     2 8.601000            8.592649
## 18  2       NA        NA     2 8.821125            8.813092
## 19  3       NA        NA     2 9.041250            9.033536
## 20  4 9.240644        NA     2 9.261375            9.253980
## 21  5       NA        NA     2 9.481500            9.474424
## 22  6 9.669264        NA     2 9.701625            9.694868</code></pre>
<p>These operations allow many to create a number of variant reference
points to be used in the calculation of synchrony.</p>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
